#!/bin/sh
if [ "$#" -eq 0 ]; then
  echo "Usage: $0 new-branch-name"
  exit 1
fi
set -e
BRANCH="git-split-$(date +%Y%m%d-%H%M%S)"
git branch "$BRANCH"
git checkout "$BRANCH"
git reset --soft master
git branch "$1"
git checkout "$1"
git branch -d "$BRANCH"
