#!/bin/sh
if [ "$#" -eq 1 ]; then
  BRANCH="$1"
  BASE="master"
elif [ "$#" -eq 2]; then
  BRANCH="$1"
  BASE="$2"
else
  echo "Usage: $0 new-branch-name [base_branch_name]"
  exit 1
fi
set -e
git checkout -B "$BRANCH"
git reset --soft "$BASE"
